/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Wizard(props) {
  const { nodes, materials } = useGLTF("/wizard.glb");
  return (
    <group {...props} dispose={null}>
      <skinnedMesh
        name="Main_Mesh"
        geometry={nodes.Main_Mesh.geometry}
        material={materials.Material}
        skeleton={nodes.Main_Mesh.skeleton}
        morphTargetDictionary={nodes.Main_Mesh.morphTargetDictionary}
        morphTargetInfluences={nodes.Main_Mesh.morphTargetInfluences}
      />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={19.937}>
        <primitive object={nodes["DEF-PELVIS"]} />
      </group>
    </group>
  );
}

useGLTF.preload("/wizard.glb");
